### PR TITLE
Render md files to an explicit location (optionally)

### PR DESCRIPTION
**Pull request by liamegan**
Resolves: https://wethecollective.teamwork.com/#/tasks/19575999

This update just provides an option to render md files to a specific location, rather than to one implied by its source path. The intention of this update is to provide a way to better organise md pages in situations where saving them to their canonical paths becomes convoluted or overbearing.

For example, for an upcoming site, we're looking at using md pages to build out news items to make news creation for clients simpler. With the current system, we have to have a file structure like this:

```
pages
├── es
│   └── news
│       └── news-item-1
│           └── index.md
├── fr
│   └── news
│       └── news-item-1
│           └── index.md
└── news
    ├── locales
    │   ├── default.yaml
    │   ├── fr.yaml
    │   └── es.yaml
    └── _news.pug
```

As a best case scenario, this structure will become quite ungainly to browse.

Instead, what this update seeks to provide is a way to store those md files in a more central location and allow the content admin to create easier to describe paths **within** the files.

So this would turn the above file structure into something like tjhis:

```
pages
└── news
    ├── locales
    │   ├── default.yaml
    │   ├── fr.yaml
    │   └── es.yaml
    ├── es
    │   └── news-item-1.md
    ├── fr
    │   └── news-item-1.md
    └── _news.pug
```

And then the source of `es/news-item-1.md` would look something like this:

```
---
template: ../_news.pug
savePath: /es/news/news-item-1/index.html
---
```

### CODE REVIEW

**Comment by marlonmarcello** [comment]
Unfortunately I don't agree with this. The pages folder is opinionated, you expect an exact behavior from it. When you look at the first file tree example you know exactly how your routes are going to be outputted but not from the second one. This is more of a patch for a use case than a complete solution. 

In my opinion I think it would be better to allow for locale files to be `md` files as well. Our current set up with gray matter would allow for yaml tags inside the `md` files which wouldn't affect how pages are currently built either.

During template compilation when crawling for locale files, we just gotta make sure we look for `md` files as well. And for page compilation we just make sure that we ignore `md` files inside the `locales/` directory.

What are your thoughts?

**Comment by marlonmarcello** [comment]
File tree example:
```
pages
└── news
    ├── locales
    │   ├── default.yaml
    │   ├── fr.yaml
    │   └── es.yaml
    ├── news-item-1
    │   └── locales
    │   │   ├── default.md
    │   │   ├── fr.md
    │   │   └── es.md
    │   └── index.pug
    └── index.pug
```

**Comment by liamegan** [comment]
Sure, I can appreciate that. Moving this to locales produces and
interesting conflict with existing locale functionality and has the
potential to introduce some ambiguity with MD files in general, but maybe
that's a matter (pun) of mofying the template level functionality.

**Comment by liamegan** [comment]
I'm going to keep this open for now and mark as DNM. This feature has some merit for another feature / usecase I'm thinking of, but will likely be canibalised for it rather than directly merged.

**Comment by marlonmarcello** [comment]
> Moving this to locales produces and interesting conflict with existing locale functionality

What's on your mind? Could you unpack that please?

> has the potential to introduce some ambiguity with MD files in general

Thought about it too, but if you think about it, it's just another extension really, it works the same way as `yaml` and maybe in the future locales could also be `json` or `toml` or whatever awesome format comes out. It just becomes an option.

**Comment by liamegan** [comment]
> > Moving this to locales produces and interesting conflict with existing locale functionality
> What's on your mind? Could you unpack that please?

This becomes a question of precedence. What I imagine doing here is consuming all of the files in the locales folder and concatenating their contents together. For example if a locales folder contains both a `default.yaml` and a `default.md` we should probably just consume both and merge their results.

**Pull request closed without merging**
