### PR TITLE
Feature/peeler update project clean

### PR DESCRIPTION
**Pull request by liamegan**
Updating the peeler to clean up both the documentation folder (which isn't necessary for peeled projects) and moving a production amplify.yml into place. Also take a look at the boots to see what I've done with the amplify.yml.

### CODE REVIEW

**Comment by marlonmarcello** [comment]
None of these updates are necessary. Both the yaml copy and the `documentation` folder is opinionated to WTC projects.  
Also, the cooker copies the files from the template repo, why not have the yaml file be named what it should be instead of making a copy of it and renaming it?

**Review by andrewrubin — COMMENTED** [review]
Sweet, looks nice @liamegan! My only suggestion would be to make the `amplify.yml` removal/copy portion conditional. I think that because this is a public-facing project, we shouldn't assume that the peel template will have either of those files.

**Comment by liamegan** [comment]
Yeha no you're absolutely right there. I wonder if there's space here to add a peeler callback that allows us to add a function that does some extra stuff post-peel.

**Comment by andrewrubin** [comment]
I was just going to say the same thing @liamegan . Some sort of customization options… Definitely worth looking into

**Comment by marlonmarcello** [comment]
@liamegan @andrewrubin look at any bootstrapper, be it `create-react-app`, or `astro init`, `vue init`, none of them have post install hooks or dependencies because it's meant to be used once, get the project ready and be done. Max that they do is cleanup their own temporary files if there are any.
I think this is creating complexity where it doesn't need to, after a project is bootstrapped it's up to the developer to remove placeholders, fill up the wholes in the config, etc. For example, all the tools mentioned above come with an index page with assets and all you gotta do is just delete it yourself.

**Comment by marlonmarcello** [comment]
Keep it lean. Keep it focused. Stay fast.

**Comment by andrewrubin** [comment]
Hmmm, yeah, I hear ya @marlonmarcello. Maybe this is an internal tool that WTC develops then. Just something we can run after a project is peeled. Thoughts @liamegan ?

**Comment by marlonmarcello** [comment]
To be fair @andrewrubin I don't see a use case right now that is complex enough to require such a tool. Looking at these changes for example all a dev would have to do is delete a documentation folder. And like I mentioned the amplify file could come with the proper name already.

**Pull request closed without merging**
